create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  company text not null default '',
  email text not null,
  whatsapp text not null default '',
  country text not null,
  service text not null,
  description text not null,
  budget text not null,
  timeline text not null,
  status text not null default 'new'
    check (status in ('new', 'reviewing', 'contacted', 'archived')),
  created_at timestamptz not null default now()
);

create index if not exists enquiries_created_at_idx
  on public.enquiries (created_at desc);
create index if not exists enquiries_status_idx
  on public.enquiries (status);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admin_users_email_idx
  on public.admin_users (lower(email));

create table if not exists private.hoza_config (
  config_key text primary key,
  value_hash bytea not null,
  updated_at timestamptz not null default now()
);

insert into private.hoza_config (config_key, value_hash)
values (
  'backend_secret_sha256',
  decode('6b6bba6afbe0ff52678fc7a454e8a048e7a867169312dcf35355ed3829b9e401', 'hex')
)
on conflict (config_key) do update
set value_hash = excluded.value_hash,
    updated_at = now();

insert into public.admin_users (email, password_hash, active)
values (
  'thrivestory@gmail.com',
  'scrypt$89Ezt8yzCiMnk40_FDARuA$6ot0aqUdf3TzxRowOjqnI7jU-kRSTx_1vsJpWsBP_piiK7I6CB1aQ-16n2Fhx1GVIJFRy6YDeYysQVOgN2__hw',
  true
)
on conflict (lower(email)) do update
set password_hash = excluded.password_hash,
    active = true,
    updated_at = now();

alter table public.enquiries enable row level security;
alter table public.admin_users enable row level security;

revoke all on table public.enquiries from anon, authenticated;
revoke all on table public.admin_users from anon, authenticated;
revoke all on all tables in schema private from public, anon, authenticated;

create or replace function private.hoza_assert_backend_secret(p_backend_secret text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_backend_secret is null or not exists (
    select 1
    from private.hoza_config
    where config_key = 'backend_secret_sha256'
      and value_hash = extensions.digest(p_backend_secret, 'sha256')
  ) then
    raise exception 'Unauthorized backend request' using errcode = '42501';
  end if;
end;
$$;

revoke all on function private.hoza_assert_backend_secret(text) from public, anon, authenticated;

create or replace function public.hoza_create_enquiry(
  p_backend_secret text,
  p_name text,
  p_company text,
  p_email text,
  p_whatsapp text,
  p_country text,
  p_service text,
  p_description text,
  p_budget text,
  p_timeline text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  enquiry_id bigint;
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  insert into public.enquiries (
    name, company, email, whatsapp, country, service,
    description, budget, timeline
  ) values (
    p_name, coalesce(p_company, ''), p_email, coalesce(p_whatsapp, ''),
    p_country, p_service, p_description, p_budget, p_timeline
  )
  returning id into enquiry_id;

  return enquiry_id;
end;
$$;

create or replace function public.hoza_admin_list_enquiries(p_backend_secret text)
returns table (
  id bigint,
  name text,
  company text,
  email text,
  whatsapp text,
  country text,
  service text,
  description text,
  budget text,
  timeline text,
  status text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select
    e.id, e.name, e.company, e.email, e.whatsapp, e.country,
    e.service, e.description, e.budget, e.timeline, e.status, e.created_at
  from public.enquiries e
  order by e.created_at desc
  limit 500;
end;
$$;

create or replace function public.hoza_admin_enquiry_stats(p_backend_secret text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  select jsonb_build_object(
    'total', count(*),
    'fresh', count(*) filter (where status = 'new'),
    'recent', count(*) filter (where created_at >= now() - interval '30 days'),
    'services', count(distinct service)
  )
  into result
  from public.enquiries;

  return result;
end;
$$;

create or replace function public.hoza_admin_update_enquiry_status(
  p_backend_secret text,
  p_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  if p_status not in ('new', 'reviewing', 'contacted', 'archived') then
    raise exception 'Invalid enquiry status' using errcode = '22023';
  end if;

  update public.enquiries
  set status = p_status
  where id = p_id;
end;
$$;

create or replace function public.hoza_admin_get_user_by_email(
  p_backend_secret text,
  p_email text
)
returns table (id bigint, email text, password_hash text, active boolean)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select u.id, u.email, u.password_hash, u.active
  from public.admin_users u
  where lower(u.email) = lower(trim(p_email))
  limit 1;
end;
$$;

create or replace function public.hoza_admin_get_user_by_id(
  p_backend_secret text,
  p_id bigint
)
returns table (id bigint, email text, active boolean)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select u.id, u.email, u.active
  from public.admin_users u
  where u.id = p_id
  limit 1;
end;
$$;

create or replace function public.hoza_admin_upsert_user(
  p_backend_secret text,
  p_email text,
  p_password_hash text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_id bigint;
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  if p_email is null or position('@' in p_email) < 2 then
    raise exception 'Invalid admin email' using errcode = '22023';
  end if;

  if p_password_hash is null or p_password_hash not like 'scrypt$%$%' then
    raise exception 'Invalid admin password hash' using errcode = '22023';
  end if;

  insert into public.admin_users (email, password_hash, active)
  values (lower(trim(p_email)), p_password_hash, true)
  on conflict (lower(email)) do update
  set password_hash = excluded.password_hash,
      active = true,
      updated_at = now()
  returning id into admin_id;

  return admin_id;
end;
$$;

revoke all on function public.hoza_create_enquiry(text, text, text, text, text, text, text, text, text, text) from public;
revoke all on function public.hoza_admin_list_enquiries(text) from public;
revoke all on function public.hoza_admin_enquiry_stats(text) from public;
revoke all on function public.hoza_admin_update_enquiry_status(text, bigint, text) from public;
revoke all on function public.hoza_admin_get_user_by_email(text, text) from public;
revoke all on function public.hoza_admin_get_user_by_id(text, bigint) from public;
revoke all on function public.hoza_admin_upsert_user(text, text, text) from public;

grant execute on function public.hoza_create_enquiry(text, text, text, text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.hoza_admin_list_enquiries(text) to anon, authenticated;
grant execute on function public.hoza_admin_enquiry_stats(text) to anon, authenticated;
grant execute on function public.hoza_admin_update_enquiry_status(text, bigint, text) to anon, authenticated;
grant execute on function public.hoza_admin_get_user_by_email(text, text) to anon, authenticated;
grant execute on function public.hoza_admin_get_user_by_id(text, bigint) to anon, authenticated;
grant execute on function public.hoza_admin_upsert_user(text, text, text) to anon, authenticated;
