create table public.article_images (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null unique,
  original_name text not null,
  mime_type text not null default 'image/webp'
    check (mime_type = 'image/webp'),
  size_bytes bigint not null
    check (size_bytes > 0 and size_bytes <= 1048576),
  width integer not null check (width > 0 and width <= 6000),
  height integer not null check (height > 0 and height <= 6000),
  created_at timestamptz not null default now(),
  check (storage_path ~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]+\.webp$'),
  check (public_url ~ '^https://')
);

create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 3 and 180),
  slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  category text not null check (char_length(trim(category)) between 2 and 80),
  excerpt text not null check (char_length(trim(excerpt)) between 20 and 500),
  content text not null check (char_length(trim(content)) >= 50),
  cover_image_url text not null,
  cover_image_path text not null references public.article_images(storage_path),
  cover_image_alt text not null check (char_length(trim(cover_image_alt)) between 3 and 180),
  author_name text not null default 'Hoza' check (char_length(trim(author_name)) between 2 and 80),
  seo_title text not null check (char_length(trim(seo_title)) between 3 and 180),
  seo_description text not null check (char_length(trim(seo_description)) between 20 and 320),
  geo_summary text not null default '' check (char_length(geo_summary) <= 800),
  status text not null default 'draft' check (status in ('draft', 'published')),
  publish_date date not null default current_date,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (publish_date, slug),
  check ((status = 'draft') or published_at is not null)
);

create index articles_status_published_at_idx
  on public.articles (status, published_at desc);
create index articles_status_category_published_at_idx
  on public.articles (status, category, published_at desc);
create index article_images_created_at_idx
  on public.article_images (created_at desc);

alter table public.article_images enable row level security;
alter table public.articles enable row level security;

revoke all on table public.article_images from anon, authenticated;
revoke all on table public.articles from anon, authenticated;

create or replace function public.hoza_admin_validate_backend_secret(
  p_backend_secret text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);
  return true;
exception
  when insufficient_privilege then
    return false;
end;
$$;

create or replace function public.hoza_admin_register_article_image(
  p_backend_secret text,
  p_storage_path text,
  p_public_url text,
  p_original_name text,
  p_size_bytes bigint,
  p_width integer,
  p_height integer
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  image_id bigint;
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  if p_storage_path is null or p_storage_path !~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]+\.webp$' then
    raise exception 'Invalid image path' using errcode = '22023';
  end if;

  if p_public_url is null or p_public_url !~ '^https://' then
    raise exception 'Invalid image URL' using errcode = '22023';
  end if;

  insert into public.article_images (
    storage_path, public_url, original_name, size_bytes, width, height
  ) values (
    p_storage_path,
    p_public_url,
    left(coalesce(nullif(trim(p_original_name), ''), 'article-image.webp'), 180),
    p_size_bytes,
    p_width,
    p_height
  )
  on conflict (storage_path) do update
  set public_url = excluded.public_url,
      original_name = excluded.original_name,
      size_bytes = excluded.size_bytes,
      width = excluded.width,
      height = excluded.height
  returning id into image_id;

  return image_id;
end;
$$;

create or replace function public.hoza_admin_list_article_images(
  p_backend_secret text
)
returns table (
  id bigint,
  storage_path text,
  public_url text,
  original_name text,
  size_bytes bigint,
  width integer,
  height integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select
    image.id,
    image.storage_path,
    image.public_url,
    image.original_name,
    image.size_bytes,
    image.width,
    image.height,
    image.created_at
  from public.article_images image
  order by image.created_at desc
  limit 200;
end;
$$;

create or replace function public.hoza_admin_create_article(
  p_backend_secret text,
  p_title text,
  p_slug text,
  p_category text,
  p_excerpt text,
  p_content text,
  p_cover_image_url text,
  p_cover_image_path text,
  p_cover_image_alt text,
  p_author_name text,
  p_seo_title text,
  p_seo_description text,
  p_geo_summary text,
  p_status text,
  p_publish_date date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  article_id bigint;
  date_code text;
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  if p_status not in ('draft', 'published') then
    raise exception 'Invalid article status' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.article_images image
    where image.storage_path = p_cover_image_path
      and image.public_url = p_cover_image_url
  ) then
    raise exception 'Select an image from the registered gallery' using errcode = '22023';
  end if;

  insert into public.articles (
    title,
    slug,
    category,
    excerpt,
    content,
    cover_image_url,
    cover_image_path,
    cover_image_alt,
    author_name,
    seo_title,
    seo_description,
    geo_summary,
    status,
    publish_date,
    published_at
  ) values (
    trim(p_title),
    lower(trim(p_slug)),
    trim(p_category),
    trim(p_excerpt),
    trim(p_content),
    p_cover_image_url,
    p_cover_image_path,
    trim(p_cover_image_alt),
    trim(p_author_name),
    trim(p_seo_title),
    trim(p_seo_description),
    trim(coalesce(p_geo_summary, '')),
    p_status,
    p_publish_date,
    case when p_status = 'published' then now() else null end
  )
  returning id into article_id;

  date_code := to_char(p_publish_date, 'YYMMDD');

  return jsonb_build_object(
    'id', article_id,
    'slug', lower(trim(p_slug)),
    'dateCode', date_code,
    'status', p_status,
    'path', '/article/' || date_code || '/' || lower(trim(p_slug))
  );
end;
$$;

create or replace function public.hoza_admin_list_articles(
  p_backend_secret text
)
returns table (
  id bigint,
  title text,
  slug text,
  category text,
  excerpt text,
  cover_image_url text,
  cover_image_alt text,
  author_name text,
  status text,
  publish_date date,
  published_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select
    article.id,
    article.title,
    article.slug,
    article.category,
    article.excerpt,
    article.cover_image_url,
    article.cover_image_alt,
    article.author_name,
    article.status,
    article.publish_date,
    article.published_at,
    article.created_at,
    article.updated_at
  from public.articles article
  order by article.created_at desc
  limit 200;
end;
$$;

create or replace function public.hoza_list_published_articles(
  p_backend_secret text
)
returns table (
  id bigint,
  title text,
  slug text,
  category text,
  excerpt text,
  cover_image_url text,
  cover_image_alt text,
  author_name text,
  publish_date date,
  published_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select
    article.id,
    article.title,
    article.slug,
    article.category,
    article.excerpt,
    article.cover_image_url,
    article.cover_image_alt,
    article.author_name,
    article.publish_date,
    article.published_at,
    article.updated_at
  from public.articles article
  where article.status = 'published'
    and article.published_at <= now()
  order by article.published_at desc
  limit 500;
end;
$$;

create or replace function public.hoza_get_published_article(
  p_backend_secret text,
  p_date_code text,
  p_slug text
)
returns table (
  id bigint,
  title text,
  slug text,
  category text,
  excerpt text,
  content text,
  cover_image_url text,
  cover_image_alt text,
  author_name text,
  seo_title text,
  seo_description text,
  geo_summary text,
  publish_date date,
  published_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hoza_assert_backend_secret(p_backend_secret);

  return query
  select
    article.id,
    article.title,
    article.slug,
    article.category,
    article.excerpt,
    article.content,
    article.cover_image_url,
    article.cover_image_alt,
    article.author_name,
    article.seo_title,
    article.seo_description,
    article.geo_summary,
    article.publish_date,
    article.published_at,
    article.updated_at
  from public.articles article
  where article.status = 'published'
    and article.published_at <= now()
    and to_char(article.publish_date, 'YYMMDD') = p_date_code
    and article.slug = lower(trim(p_slug))
  limit 1;
end;
$$;

revoke all on function public.hoza_admin_validate_backend_secret(text) from public;
revoke all on function public.hoza_admin_register_article_image(text, text, text, text, bigint, integer, integer) from public;
revoke all on function public.hoza_admin_list_article_images(text) from public;
revoke all on function public.hoza_admin_create_article(text, text, text, text, text, text, text, text, text, text, text, text, text, text, date) from public;
revoke all on function public.hoza_admin_list_articles(text) from public;
revoke all on function public.hoza_list_published_articles(text) from public;
revoke all on function public.hoza_get_published_article(text, text, text) from public;

grant execute on function public.hoza_admin_validate_backend_secret(text) to anon, authenticated, service_role;
grant execute on function public.hoza_admin_register_article_image(text, text, text, text, bigint, integer, integer) to anon, authenticated;
grant execute on function public.hoza_admin_list_article_images(text) to anon, authenticated;
grant execute on function public.hoza_admin_create_article(text, text, text, text, text, text, text, text, text, text, text, text, text, text, date) to anon, authenticated;
grant execute on function public.hoza_admin_list_articles(text) to anon, authenticated;
grant execute on function public.hoza_list_published_articles(text) to anon, authenticated;
grant execute on function public.hoza_get_published_article(text, text, text) to anon, authenticated;
